name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-xlarge
    steps:
    - uses: actions/checkout@v1
    - uses: dtolnay/rust-toolchain@stable
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - run: cargo build --all --locked
    - run: cargo test --all --locked
    - name: Check
      run: |
        cargo fmt -- --check
        cargo clippy
    - name: Print sccache statistics
      shell: bash
      run: ${SCCACHE_PATH} --show-stats
